version: '3.2'

services:
  gitlab:
    image: middleware/gitlab
    container_name: gitlab
    privileged: true
    restart: always
    build: .
    ports:
      - '80:80'
    volumes:
      - gitlab-data:/var/opt/gitlab/git-data/repositories
    networks:
     - gitlab-net
    environment:
      TZ: 'Asia/Shanghai'
      GITLAB_OMNIBUS_CONFIG: |
         external_url 'http://192.168.0.109'
         gitlab_rails['time_zone'] = 'Asia/Shanghai'
         gitlab_rails['smtp_enable'] = true
         gitlab_rails['smtp_address'] = "smtp.163.com"
         gitlab_rails['smtp_port'] = 25
         gitlab_rails['smtp_user_name'] = "huacke@163.com"
         gitlab_rails['smtp_password'] = "huacke"
         gitlab_rails['smtp_domain'] = "163.com"
         gitlab_rails['smtp_authentication'] = "login"
         gitlab_rails['smtp_enable_starttls_auto'] = true
         gitlab_rails['smtp_tls'] = true
         gitlab_rails['gitlab_email_from'] = 'huacke@163.com'
         gitlab_rails['gitlab_shell_ssh_port'] = 2222
networks:
  gitlab-net:
    driver: bridge
volumes:
  gitlab-data: 
    driver: local-persist #docker本地数据持久化插件
    driver_opts: 
      mountpoint: /data/dockerData/gitlab/repositories

    
